name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle Build
        working-directory: ./SmartCarMQTTApp
        run: ./gradlew build
      - name: Run unit testing
        working-directory: ./SmartCarMQTTApp
        run: ./gradlew test  
        
  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Make gradlew available
        run: |
            cd SmartCarMQTTApp
            chmod +x gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run instrumented tests for SmartCarMQTTApp
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: Nexus 6
          api-level: 30
          arch: x86_64
          working-directory: ./SmartCarMQTTApp
          script: ./gradlew connectedCheck --stacktrace